name: Codex task
description: Small, green-build patch request for Codex
title: "Codex: <one-liner>"
labels: ["codex"]
body:
  - type: markdown
    attributes:
      value: |
        Follow `.github/CODEX.md` Patch Rules. Keep diff tiny and compiling.
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What to implement (paste acceptance criteria + any stubs).
      placeholder: |
        - Add PulseScreen composable gated by FeatureToggles.PULSE_ENABLED
        - Add nav route "pulse" and a button in Home ONLY when toggle true
        - No experimental APIs; no version bumps
    validations:
      required: true
