name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # IMPORTANT: pin to Gradle 8.7 (do NOT use latest 9.x)
      - name: Set up Gradle (8.7 system)
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 8.7
          cache-read-only: false

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Single build step — use system 'gradle' (no ./gradlew)
      - name: Build Debug APK with Gradle 8.7
        run: gradle --no-daemon clean :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
