name: Android APK

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Setup Gradle (new action)
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build both flavors (Lite + Pro)
        run: |
          ./gradlew clean \
            :app:assembleCoreDebug \
            :app:assembleFullDebug \
            --stacktrace --info

      - name: Show APKs produced
        run: |
          echo "== APKs =="
          find app/build/outputs/apk -type f -name "*.apk" -printf "%p\n" || true

      - name: Collect both APKs
        run: |
          mkdir -p artifacts
          cp -v app/build/outputs/apk/core/debug/*.apk artifacts/ 2>/dev/null || true
          cp -v app/build/outputs/apk/full/debug/*.apk artifacts/ 2>/dev/null || true
          echo "== Collected =="
          ls -la artifacts

      - name: Upload both APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks-${{ github.ref_name }}-${{ github.run_number }}
          path: artifacts/*.apk
          if-no-files-found: error
          retention-days: 14
