name: Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK (Gradle action, no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean :app:assembleDebug --stacktrace --info --no-daemon

      - name: Show outputs tree
        if: always()
        run: |
          echo "== app/build/outputs =="
          ls -R app/build/outputs || true

      - name: Collect APKs (robust find)
        if: always()
        run: |
          mkdir -p artifacts
          find app/build/outputs -type f \( -name "*.apk" -o -name "*.aab" \) -print -exec cp -v {} artifacts/ \; || true
          echo "== Artifacts collected =="
          ls -l artifacts || true

      - name: Upload APK artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: artifacts/*

      - name: Upload debug reports on failure (manifests, reports, logs)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-info
          path: |
            app/build/outputs/**
            app/build/reports/**
            app/build/intermediates/manifest_merge_report/**/AndroidManifest.xml
          if-no-files-found: warn
