name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: android-actions/setup-android@v3
      - run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean :app:assembleDebug
      - run: |
          mkdir -p artifacts
          cp -r app/build/outputs/apk/**/**/*.apk artifacts/ || true
          ls -R artifacts || true
      - uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: artifacts/*.apk
          if-no-files-found: error
