name: Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK (Gradle action, no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean :app:assembleCoreDebug --stacktrace --info --no-daemon

      - name: Show outputs tree
        if: always()
        run: |
          echo "== app/build/outputs =="
          ls -R app/build/outputs || true

      - name: Collect APKs (robust find)
        if: always()
        run: |
          mkdir -p artifacts
          # copy core flavor first (expected)
          cp -v app/build/outputs/apk/core/debug/*.apk artifacts/ 2>/dev/null || true
          # fallbacks (in case AGP layout differs)
          cp -v app/build/outputs/apk/**/debug/*.apk artifacts/ 2>/dev/null || true
          find app/build/outputs -name "*.apk" -maxdepth 5 -print -exec cp -v {} artifacts/ \; 2>/dev/null || true
          echo "Artifacts:" && ls -l artifacts || true
