name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: gradle/actions/setup-gradle@v3.5.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: android-actions/setup-android@v3
      - run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean :app:assembleDebug
      - name: Copy APK to artifacts folder
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/ || true
          ls -R artifacts || true
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SecondMind-debug
          path: artifacts/*.apk
          if-no-files-found: error
