name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK (Gradle action, no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean :app:assembleDebug --stacktrace --info --no-daemon --no-build-cache --rerun-tasks

      - name: Collect APKs
        run: |
          mkdir -p artifacts
          cp -v app/build/outputs/apk/debug/*.apk artifacts/ || true
          echo "Artifacts:" && ls -l artifacts || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: artifacts/*.apk
          if-no-files-found: error

      - name: Upload build logs on failure
        if: failure()
        run: |
          mkdir -p logs
          find . -type f \( -name "*.log" -o -name "*.kotlin_module" -o -name "kotlin-compiler*" \) -print0 | xargs -0 -I{} bash -lc 'dest=logs/$(echo {} | sed s#^\./##); mkdir -p "$(dirname "$dest")"; cp -v "{}" "$dest" || true'
          cp -vR app/build/reports logs/ || true
      - name: Upload logs artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs
          if-no-files-found: warn
