name: Green Check
on:
  pull_request: { branches: [ main ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17', cache: gradle }
      - uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
      - name: Install SDK
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Build (no version bumps, just compile)
        run: ./gradlew --no-daemon -q :app:compileDebugKotlin :app:compileDebugJavaWithJavac :app:assembleDebug testDebugUnitTest
