name: Green Check (mirror of Android APK)
on:
  pull_request: { branches: [ main ] }
  workflow_dispatch:
concurrency:
  group: green-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK (same as main)
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Provision the same Gradle version your green jobs use
      - name: Setup Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 8.7

      - name: Build (mirror main)
        run: gradle --no-daemon clean :app:assembleDebug

      - name: Upload APK artifact (mirror main)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
