name: Green Check
on:
  pull_request: { branches: [ main ] }
  workflow_dispatch:
concurrency:
  group: gc-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
      - name: Install Android SDK packages
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Setup Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3.5.0
      - name: Build (assemble only, mirrors android-apk.yml)
        run: gradle --no-daemon clean :app:assembleDebug
